cmd/gocharm: build without 'src' directory, -no-source flag
juju/gocharm pull request #52
Opened 2016-01-21 20:31 UTC by mever

Resolves #33

2016-09-26 17:20 UTC, rogpeppe commented on cmd/gocharm/main.go
> +		if name == "src" && *noSource && !*source {
Given that if *noSource is true, *source must be false, I think this is equivalent to:

    if *noSource && name == "src" {
        continue
    }

(I also swapped the two exprs as I think it reads more nicely that way)

2016-09-26 17:20 UTC, rogpeppe commented on cmd/gocharm/main.go
> +	if *source && *noSource {
All the other usage checking is directly in main, so I'd do this check there too, I think.

2016-09-26 17:22 UTC, rogpeppe requested changes
LGTM modulo a couple of minor suggestions, thanks!

(and so sorry it's taken 9 months for me to notice this PR)

2017-09-08 07:45 UTC, mever commented
Hi @rogpeppe, do not worry about the 9 months. It took me almost a year. :sweat_smile: (I am very busy and this is a side project for me). Anyway, I found some time to throw at this project again.

2021-06-19 19:57 UTC, closed without merging